spring:
  profiles:
    active:
    -  dev

---
spring:
  profiles: dev #开发环境
  application:
    name: outmission-config-dev
server:
  port: 8201

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
spring:
  profiles: test #测试环境
  application:
    name: outmission-config-test
server:
  port: 8202
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#保存一定为UTF-8格式