spring:
  profiles:
    active:
    -  dev

---
spring:
  profiles: dev #开发环境
  application:
    name: outmission-config-dev

---
spring:
  profiles: test #测试环境
  application:
    name: outmission-config-test

#保存一定为UTF-8格式