spring:
  profiles:
    active:
    -  dev

---
spring:
  profiles: dev #开发环境
  application:
    name: outmission-web-client
server:
  port: 8001

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
spring:
  profiles: test #测试环境
  application:
    name: outmission-web-client
server:
  port: 8002
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
#保存一定为UTF-8格式